module.exports = {
  rules: {
    'generator-star-spacing': 'off',
    'func-names': 0,
    'linebreak-style': 0,
    semi: 0,
    'no-return-await': 0,
    'comma-dangle': 0,
    'space-before-function-paren': 0,
    'arrow-parens': 0,
    quotes: 0,
    'space-unary-ops': 0,
    'class-methods-use-this': 0,
    radix: 0,
    'object-curly-newline': 0,
    'operator-linebreak': 0,
    'implicit-arrow-linebreak': 0,
    'spaced-comment': 0,
    'consistent-return': 0,
    'prefer-const': 1,
    'max-len': ['warn', { code: 200 }],
    'prefer-template': 0,
    indent: 0,
    camelcase: 0,
    'eol-last': 0,
    'lines-between-class-members': 0,
    'array-callback-return': 'warn',
    'default-case': 0,
    'dot-location': ['warn', 'property'],
    eqeqeq: 0,
    'new-parens': 'warn',
    'require-yield': 'warn',
    'rest-spread-spacing': ['warn', 'never'],
    strict: ['warn', 'never'],
    'unicode-bom': ['warn', 'never'],
    'use-isnan': 'warn',
    'valid-typeof': 'warn',
    'max-classes-per-file': 0,
    'arrow-body-style': 0,
    'function-paren-newline': 0,
    // 对象解构，数组不强制解构
    'prefer-destructuring': ['warn', { object: true, array: false }],
    'space-before-blocks': 'warn',
    'space-infix-ops': 'warn',
    'prefer-promise-reject-errors': 0,
  },
}
